class CreateMbtis < ActiveRecord::Migration
  def change
    create_table :mbtis do |t|
      t.string :type
      t.integer :user_id
      t.float :Sg
      t.float :Ng
      t.float :Tg
      t.float :Fg
      t.float :Jg
      t.float :Pg
      t.float :En
      t.float :In
      t.string :q1
      t.string :q2
      t.string :q3
      t.string :q4
      t.string :q5
      t.string :q6
      t.string :q7
      t.string :q8
      t.string :q9
      t.string :q10
      t.string :q11
      t.string :q12
      t.string :q13
      t.string :q14
      t.string :q15
      t.string :q16
      t.string :q17
      t.string :q18
      t.string :q19
      t.string :q20
      t.string :q21
      t.string :q22
      t.string :q23
      t.string :q24
      t.string :q25
      t.string :q26
      t.string :q27
      t.string :q28
      t.string :q29
      t.string :q30
      t.string :q31
      t.string :q32
      t.string :q33
      t.string :q34
      t.string :q35
      t.string :q36
      t.string :q37
      t.string :q38
      t.string :q39
      t.string :q40
      t.string :q41
      t.string :q42
      t.string :q43
      t.string :q44
      t.string :q45
      t.string :q46
      t.string :q47
      t.string :q48
      t.string :q49
      t.string :q50
      t.string :q51
      t.string :q52
      t.string :q53
      t.string :q54
      t.string :q55
      t.string :q56
      t.string :q57
      t.string :q58
      t.string :q59
      t.string :q60
      t.string :q61
      t.string :q62
      t.string :q63
      t.string :q64
      t.string :q65
      t.string :q66
      t.string :q67
      t.string :q68
      t.string :q69
      t.string :q70

      t.timestamps
    end
    add_index :mbtis, :user_id
  end
end
